language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
env:
- CI=true
jobs:
  include:
  - stage: Tests
    name: ES Lint
    script: yarn test:lint:js
  - name: Unit Test Execution
    script: yarn test
  - stage: deployment
    name: Deploy artifacts to Heroku
    deploy:
      provider: heroku
      app: ps-spacext
      api_key:
        secure: jBt1bnLTfRtjZPTHiLyEJkSwoNz+oaEnPJrxeug3LFvJh7/gi0xnooSEoElIyP0B6z2QW+DRylYOOXHnE7rlmVZ4DWo0bG12W4OpY9STuXk87Da3Cci3EZ+rJ14C6f/IJ/aNrK37bHhTD6t2YKNsr8z+Lggdp6FcCpJZTdZx1iTq+P3ZsU5E3m8WwlJTIUaMxowvt+WIY6bvMyFm8DXwBMI4MmKw0NNrVUiIiD/u+qF1/dKQ8sUvVhca3lxy91XCMAkclZQ0eCc9XqHvhR0tOGCW+zI/HWaDSiFinClGZDkdDAp64Pvvu/+ACT0hT53wO6t+M4/mVWzXC9RER4wwLXlsiE/yHt2XUk/0p7tCIQ18GDRGOcgtE2yHkn8y9gfY1QV4OTiUBgTmNZ2rokVuIWNSUHIBOJ35vWcmkYzQh5B2QGCBEpaNvG9RsiUBaCWgW0YANg7PuqXQ3/WPAz78/QiBeLsn/b3mOdajVk5L5qZ5tbg3oPYKjpORg88168e9zyJJKTNvS11aqHykAjZ0IBbALToBebrfr4oDpXD9Mxh5eA2UQkbXvLFFQr+t6cUBa8evwbnDS1p3HEkx2e38dllzJMSA+syYnEuBTrDF5wgKRFwcHMn1PNdAvaHojVp5GH3Lbpgp+nz2Xqzw+mciSQgMujvlsT1f1j3xAw8XwMM=
